### ISSUE TITLE
No GPG signatures for the Raspberry Pi images

### ISSUE THREAD

**Issue by stafwag** [manjaro-arm/rpi4-images#8]
Most Manjaro-ARM images have GPG signatures but there are no GPG signatures available for the Raspberry Pi images.

Any reason why there are no GPG signatures available for the raspberry pi images?
Can you make them available?

Kind regards,

--
staf

**Comment by Strit** [comment]
Since we switched to using Githubs CI infrastructure, it has not been possible to create signatures for the images.

We are still looking into how we could do this, but there is nothing working right now.

In the meantime, sha1 checksums should be good enough to verify that the image is complete and correct.
